{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "attachments": [{"name": "API Response", "source": "79ca8500-0cde-4169-81fd-dff27cfe0e72-attachment.json", "type": "application/json"}, {"name": "log", "source": "70a655e6-0cfb-4bd5-9c49-bff6dff12de4-attachment.txt", "type": "text/plain"}], "start": 1736830897535, "stop": 1736830898637, "uuid": "963dc43c-8a28-4410-bdd1-fb8de324e23b", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "tag", "value": "tags('API_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "15096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}